import { VaultResponse } from '@/lib/api-types';

/**
 * My Vault 프론트엔드 UI 개발용 Mock 데이터
 * API 연동 전 UI/UX 검증에 사용
 */

export const MOCK_VAULT_DATA: VaultResponse = {
  user: {
    id: 'user-mock-1',
    name: 'K-pop Collector',
    image: 'https://via.placeholder.com/40x40?text=User',
    collectorIndex: 2450,
  },
  stats: {
    totalCards: 87,
    inHandCount: 67,
    wishlistCount: 15,
    tradeCount: 5,
    completeSetCount: 3,
  },
  cards: [
    {
      id: 'binder-1',
      cardId: 'card-1',
      cardSlug: 'twice-tzuyu-feel-special',
      cardName: 'TZUYU - Feel Special',
      groupName: 'TWICE',
      memberName: 'TZUYU',
      albumTitle: 'Feel Special',
      imageUrl: 'https://via.placeholder.com/280x400?text=TZUYU+Feel+Special',
      thumbImagePath: '/thumbs/twice-tzuyu-feel-special.webp',
      tags: ['In Hand', 'Complete'],
      note: '홀로그램 카드, 매우 좋은 상태',
      dimensions: { width: 56, height: 87 },
      compatibleSleeves: ['Standard 56x87mm', 'Premium 60x90mm'],
      estimatedPrice: 45.99,
      ownedCount: 234,
      wishedCount: 1892,
      addedAt: '2024-01-15T08:30:00Z',
      updatedAt: '2024-08-10T14:20:00Z',
    },
    {
      id: 'binder-2',
      cardId: 'card-2',
      cardSlug: 'blackpink-jennie-aptober',
      cardName: 'JENNIE - APTOBER',
      groupName: 'BLACKPINK',
      memberName: 'JENNIE',
      albumTitle: 'APTOBER',
      imageUrl: 'https://via.placeholder.com/280x400?text=JENNIE+APTOBER',
      thumbImagePath: '/thumbs/blackpink-jennie-aptober.webp',
      tags: ['In Hand'],
      note: null,
      dimensions: { width: 56, height: 87 },
      compatibleSleeves: ['Standard 56x87mm', 'Premium 60x90mm'],
      estimatedPrice: 89.5,
      ownedCount: 156,
      wishedCount: 2341,
      addedAt: '2024-02-20T10:45:00Z',
      updatedAt: '2024-08-09T16:00:00Z',
    },
    {
      id: 'binder-3',
      cardId: 'card-3',
      cardSlug: 'exo-sehun-obsession',
      cardName: 'SEHUN - Obsession',
      groupName: 'EXO',
      memberName: 'SEHUN',
      albumTitle: 'Obsession',
      imageUrl: 'https://via.placeholder.com/280x400?text=SEHUN+Obsession',
      thumbImagePath: '/thumbs/exo-sehun-obsession.webp',
      tags: ['ISO', '#드볼중'],
      note: '구매처: eBay 추천',
      dimensions: { width: 56, height: 87 },
      compatibleSleeves: ['Standard 56x87mm', 'Premium 60x90mm'],
      estimatedPrice: 35.0,
      ownedCount: 89,
      wishedCount: 734,
      addedAt: '2024-03-10T12:15:00Z',
      updatedAt: '2024-08-08T09:30:00Z',
    },
    {
      id: 'binder-4',
      cardId: 'card-4',
      cardSlug: 'stray-kids-felix-noeasy',
      cardName: 'FELIX - NOEASY',
      groupName: 'Stray Kids',
      memberName: 'FELIX',
      albumTitle: 'NOEASY',
      imageUrl: 'https://via.placeholder.com/280x400?text=FELIX+NOEASY',
      thumbImagePath: '/thumbs/stray-kids-felix-noeasy.webp',
      tags: ['In Hand', 'Trade Bait'],
      note: null,
      dimensions: { width: 56, height: 87 },
      compatibleSleeves: ['Standard 56x87mm', 'Premium 60x90mm'],
      estimatedPrice: 12.99,
      ownedCount: 456,
      wishedCount: 1245,
      addedAt: '2024-04-05T14:20:00Z',
      updatedAt: '2024-08-07T11:00:00Z',
    },
    {
      id: 'binder-5',
      cardId: 'card-5',
      cardSlug: 'seventeen-jeonghan-god-smile',
      cardName: 'JEONGHAN - God\'s Smile',
      groupName: 'SEVENTEEN',
      memberName: 'JEONGHAN',
      albumTitle: 'God\'s Smile',
      imageUrl: 'https://via.placeholder.com/280x400?text=JEONGHAN+God',
      thumbImagePath: '/thumbs/seventeen-jeonghan-god-smile.webp',
      tags: ['In Hand', 'Complete'],
      note: '한정판, 시즌초 구매',
      dimensions: { width: 56, height: 87 },
      compatibleSleeves: ['Standard 56x87mm', 'Premium 60x90mm'],
      estimatedPrice: 125.99,
      ownedCount: 45,
      wishedCount: 567,
      addedAt: '2024-05-12T16:45:00Z',
      updatedAt: '2024-08-06T13:20:00Z',
    },
  ],
  filters: {
    tags: ['In Hand', 'Complete', 'ISO', '#드볼중', 'Trade Bait'],
    groups: ['TWICE', 'BLACKPINK', 'EXO', 'Stray Kids', 'SEVENTEEN'],
  },
  timestamp: new Date().toISOString(),
};
